mazurylabs/mazury-frontend

.storybook/main.js, .storybook/preview.js, components/Button.stories.tsx, package.json, yarn.lock
This PR adds [Storybook](https://storybook.js.org/) - a tool that lets you develop UI components in isolation. With our expanding design/UI needs, I feel like this is a good time to add Storybook to reliably develop our components in isolation. This will let us maintain our library of components easily.
=> Add storybook

.github/workflows/ci.yaml, components/Button.test.tsx, jest.config.js, jest.setup.js, package.json, yarn.lock
This PR adds Jest and [Testing Library](https://testing-library.com/docs/react-testing-library/intro/) to our project. I have also added a CI workflow that will run our tests on all of our PRs from now on.
=> [MAZ-86] Add testing suite

.storybook/main.js, components/Layout/Layout.tsx, components/MobileSidebar/MobileSidebar.stories.tsx, components/ReferralPreview.tsx, components/Sidebar.tsx, package.json, pages/_app.tsx, pages/index.tsx, pages/people/[address].tsx, tsconfig.json, yarn.lock
Closes #7 
This PR lets you do
```tsx
import { Button } from 'components';
```
instead of having to do
```tsx
import { Button } from '../../components';
```
=> Implement absolute imports

pages/people/[address].tsx
=> Make load more buttons on the profile page functional

components/Button/index.tsx, components/OnboardingLayout/OnboardingLayout.tsx, components/index.ts, hooks/index.ts, hooks/useIntersection.ts, pages/people/[address].tsx
Closes #18
Closes #10 
Closes #9
More commits to follow
=> Moaaarrrrrrrrr bug fixes

pages/people/[address].tsx
Closes #23 
Will do more changes in a future PR once Sebastian gives me designs for this. Temp fixes for now
=> Handle the case when a profile is empty

pages/people/[address].tsx
=> Update empty state messages

components/Card/Card.stories.tsx, components/Card/Card.test.tsx, components/Card/Card.tsx, components/Card/__snapshots__/Card.test.tsx.snap, components/Card/index.tsx, components/Toggle/Toggle.stories.tsx, components/Toggle/Toggle.test.tsx, components/Toggle/Toggle.tsx, components/Toggle/__snapshots__/Toggle.test.tsx.snap, components/Toggle/index.tsx, public/icons/toggle-off.svg, public/icons/toggle-on.svg
This PR adds the `Card` and `Toggle` components.
=> Sync component library with the style guide

components/OnboardingLayout/OnboardingLayout.tsx, contexts/index.ts, pages/_app.tsx, pages/onboarding/socials.tsx, utils/api.ts, views/Onboarding/Profile.tsx
=> Integrate avatar upload

hooks/useMirrorPosts.ts, package.json, pages/people/[address].tsx, types.ts, yarn.lock
Thanks @wojtekwtf for the help! Had to open a new PR because there were some issues with `node_modules` in your PR & lock files.
=> [MAZ-192] Integrate Mirror API

components/Layout/Layout.tsx, components/Layout/__snapshots__/Layout.test.tsx.snap
=> Fix for layout breaking issue

components/BadgePreview.tsx, hooks/useBadges.ts, hooks/useMirrorPosts.ts, hooks/useReferrals.ts, package.json, pages/people/[address].tsx, utils/index.ts, yarn.lock
Several profile page improvements
=> [MAZ-241] Profile page sprint

components/Modal/Modal.tsx, components/Modal/__snapshots__/Modal.test.tsx.snap
=> Issue 50: Fixed scroll issue with modal

components/Skeleton/Skeleton.stories.tsx, components/Skeleton/Skeleton.tsx, components/Skeleton/index.ts, components/index.ts, hooks/useProfile.ts, pages/people/[address].tsx, utils/index.ts, views/Profile/LoadingState.tsx
- Profile page data is now loaded on the client instead of the server to prevent a long delay
- Implemented loading skeletons prepared by Sebastian
=> [MAZ-287] Implement loading skeletons for profile page

views/Search/ResultState.tsx, views/Search/SearchPage.tsx
=> [MAZ-436] - Change default search view to profile list

views/Search/BadgeFilter.tsx, views/Search/SearchPage.tsx, views/Search/SkillFilter.tsx
- just a small hotfix related to textbox placeholders
=> Release 0.0.1

components/Pill/Pill.tsx, hooks/useIntersection.ts, pages/index.tsx, pages/people/[address].tsx, types.ts, utils/index.ts, views/Search/IdleState.tsx, views/Search/InitialFilterState.tsx, views/Search/ResultState.tsx, views/Search/Search.tsx
*Everywhere besides "Mazury Badges"
=> Change badges to credentials everywhere in frontend

pages/_app.tsx, utils/index.ts, views/SignIn/SignInModal.tsx
* Updated to clear wagmi data from local storage
* updated to clear once app loads
=> Hotfix walletconnect auth

hooks/useIntersect.ts, views/Search/ResultState.tsx
Co-authored-by: Chris <christianotu.d@gmail.com>
=> Deploy infinite scroll hotfix

components/FeedbackFishButton.jsx, package.json, pages/_app.tsx, yarn.lock
* Add feedbackfish button
* Changed style for the feedback button
* Add light shadow to the button
=> Deploy feedback button

pages/people/[address].tsx, views/Search/ResultState.tsx, views/Search/SearchPage.tsx
* make address and search public
* enable search for users not logged in
* make result state public
=> Temporarily open search to logged out users

pages/opportunities/[opportunityId]/applicants/index.tsx
=> Add more fileds in the applicant view
